{% set name = "fastai" %}
{% set version = "2.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastai-{{ version }}.tar.gz
  sha256: e5ac80ff46dd8070c670a348f31a64c85ea1a91dc320c2106488f34333282916

build:
  entry_points:
    - configure_accelerate=fastai.distributed:configure_accelerate
  # torchvision doesn't support s390x or ppc64le
  skip: true  # [py<37 or s390x or ppc64le]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - packaging
    - fastdownload >=0.0.5,<2
    - fastcore >=1.5.29,<1.6
    - torchvision >=0.8.2
    - matplotlib-base
    - pandas
    - requests
    - pyyaml
    - fastprogress >=0.2.4
    - pillow >6.0.0
    - scikit-learn
    - scipy
    - spacy <4
    - pytorch >=1.7,<2.1

test:
  imports:
    - fastai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastai
  summary: fastai simplifies training fast and accurate neural nets using modern best practices
  description: |
    fastai is a deep learning library which provides practitioners with high-level components
    that can quickly and easily provide state-of-the-art results in standard deep learning
    domains, and provides researchers with low-level components that can be mixed and matched to
    build new approaches.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/fastai/fastai
  doc_url: https://docs.fast.ai/

extra:
  recipe-maintainers:
    - giswqs
